version: '3.8'

services:
  # Nginx reverse proxy with Let's Encrypt SSL
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"      # Standard HTTP port for Let's Encrypt
      - "443:443"    # Standard HTTPS port
    volumes:
      - ./nginx-letsencrypt.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - frontend
      - mcore
    restart: unless-stopped
    networks:
      - samfms-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Certbot for Let's Encrypt SSL
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet; sleep 12h & wait $${!}; done;'"

networks:
  samfms-network:
    driver: bridge
