services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
  mcore:
    build: ./Core
    command: sh -c "pip install -r requirements.txt && python main.py"
    volumes:
      - ./Core:/app
    ports:
      - '8000:8000'
    depends_on:
      - rabbitmq
  gps_service:
    build: ./Sblocks/gps
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./Sblocks/gps:/app
    ports:
      - '8001:8000'
    depends_on:
      - rabbitmq
  trip_planning_service:
    build: ./Sblocks/trip_planning
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./Sblocks/trip_planning:/app
    ports:
      - '8002:8000'
    depends_on:
      - rabbitmq
  vehicle_maintenance_service:
    build: ./Sblocks/vehicle_maintainence
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./Sblocks/vehicle_maintainence:/app
    ports:
      - '8003:8000'
    depends_on:
      - rabbitmq
  frontend:
    build: ./Frontend/samfms
    ports:
      - '3000:3000'
    depends_on:
      - mcore
