version: "3.9"

services:
  mongo:
    image: mongo:7
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })' || exit 1"]
      interval: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      retries: 10
      start_period: 20s

  mcore:
    build:
      context: ./Core
      dockerfile: Dockerfile
      target: test           
    environment:
      MONGO_URI: mongodb://mongo:27017
    volumes:
      - ./Core:/app          
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
