services:
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - samfms-network

  mongodb:
    image: mongo:4.4
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - samfms-network

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - samfms-network

  security:
    build: ./Sblocks/security
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MONGODB_URL=${MONGODB_URL:-mongodb://samfms_admin:SafeMongoPass2025%21SecureDB%40SAMFMS@mongodb:27017}
      - DATABASE_NAME=${DATABASE_SECURITY:-samfms_security}
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://samfms_rabbit:RabbitPass2025%21@rabbitmq:5672/}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-15}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS:-7}
      - ENVIRONMENT=${ENVIRONMENT:-test}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SERVICE_STARTUP_DELAY=0
      - RABBITMQ_CONNECTION_RETRY_ATTEMPTS=10
      - RABBITMQ_CONNECTION_RETRY_DELAY=1
    networks:
      - samfms-network

  core:
    build:
      context: .
      dockerfile: ./Core/Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      security:
        condition: service_started
    environment:
      - MONGODB_URL=${MONGODB_URL:-mongodb://samfms_admin:SafeMongoPass2025%21SecureDB%40SAMFMS@mongodb:27017}
      - DATABASE_NAME=${DATABASE_CORE:-samfms_core}
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://samfms_rabbit:RabbitPass2025%21@rabbitmq:5672/}
      - SECURITY_URL=http://security:8000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-15}
      - ENVIRONMENT=${ENVIRONMENT:-test}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SERVICE_STARTUP_DELAY=0
      - RABBITMQ_CONNECTION_RETRY_ATTEMPTS=10
      - RABBITMQ_CONNECTION_RETRY_DELAY=1
    networks:
      - samfms-network

networks:
  samfms-network:
    driver: bridge