services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
  mcore:
    build: ./Core
    command: sh /app/start.sh # Changed to execute the start.sh script
    volumes:
      - ./Core:/app
    ports:
      - '8000:8000'
      - '27017:27017' # Exposed MongoDB port
    depends_on:
      - rabbitmq
  gps_service:
    build: ./Sblocks/gps
    command: sh /app/start.sh # Changed to execute the start.sh script
    volumes:
      - ./Sblocks/gps:/app
    ports:
      - '8001:8000'
      - '27018:27017' # Exposed MongoDB port for GPS
    depends_on:
      - rabbitmq
  trip_planning_service:
    build: ./Sblocks/trip_planning
    command: sh /app/start.sh # Changed to execute the start.sh script
    volumes:
      - ./Sblocks/trip_planning:/app
    ports:
      - '8002:8000'
      - '27019:27017' # Exposed MongoDB port for Trip Planning
    depends_on:
      - rabbitmq
  vehicle_maintenance_service:
    build: ./Sblocks/vehicle_maintainence
    command: sh /app/start.sh # Changed to execute the start.sh script
    volumes:
      - ./Sblocks/vehicle_maintainence:/app
    ports:
      - '8003:8000'
      - '27020:27017' # Exposed MongoDB port for Vehicle Maintenance
    depends_on:
      - rabbitmq
  frontend:
    build: ./Frontend/samfms
    ports:
      - '3000:3000'
    depends_on:
      - mcore
