version: '3.8'

services:
  # Nginx reverse proxy with SSL
  nginx:
    image: nginx:alpine
    ports:
      - "21023:80"    # HTTP within your port range
      - "21024:443"   # HTTPS within your port range
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl-certs:/etc/ssl/certs:ro
      - ./ssl-private:/etc/ssl/private:ro
    depends_on:
      - frontend
      - mcore
    restart: unless-stopped
    networks:
      - samfms-network
    command: "/bin/sh -c 'nginx -g \"daemon off;\"'"

networks:
  samfms-network:
    driver: bridge
