[tool.pytest.ini_options]
# Test discovery
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

# Markers
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
    "e2e: End-to-end tests",
    "slow: Slow tests",
    "database: Tests requiring database",
    "rabbitmq: Tests requiring RabbitMQ",
    "auth: Authentication tests",
    "api: API tests",
    "service: Service tests",
    "asyncio: Async tests"
]

# Async testing
asyncio_mode = "auto"

# Test output
addopts = [
    "-v",
    "--tb=short",
    "--strict-markers",
    "--disable-warnings",
    "--color=yes",
    "--durations=10"
]

# Minimum version requirements
minversion = "6.0"

# Test timeout
timeout = 300

# Logging
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(name)s: %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

# Test filtering
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
    "ignore::UserWarning"
]

# Test collection
collect_ignore = [
    "build",
    "dist",
    "*.egg-info",
    "node_modules",
    "venv",
    ".venv",
    "__pycache__"
]

# Test environment
env = [
    "ENVIRONMENT=test",
    "LOG_LEVEL=DEBUG",
    "MONGODB_URL=mongodb://localhost:27017/samfms_test",
    "RABBITMQ_HOST=localhost",
    "RABBITMQ_PORT=5672",
    "JWT_SECRET=test-jwt-secret-key"
]
