name: CI

# ───────────────────────────
# Trigger ONLY on pushes to main
# ───────────────────────────
on:
  push:
    branches:
      - main

# Cancel overlapping main builds to save minutes
concurrency:
  group: ci-main
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3       # hard kill-switch for hung runs

    steps:
    # 1. Check out code
    - uses: actions/checkout@v4

    # 2. Enable BuildKit (optional but harmless)
    - uses: docker/setup-buildx-action@v3

    # 3. Build the lean test image and start the minimal stack
    - name: Build images & start services
      run: |
        docker compose -f docker-compose.test.yml build --pull
        docker compose -f docker-compose.test.yml up -d --wait --wait-timeout 60

    # 4. Run the unit tests
    - name: Run pytest
      run: |
        docker compose -f docker-compose.test.yml run --rm mcore

    # 5. Clean up to free runner disk
    - name: Tear down stack
      if: always()
      run: |
        docker compose -f docker-compose.test.yml down -v --remove-orphans
        docker system prune -af
