name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup QEMU and buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images & start minimal services
        run: |
          docker compose -f docker-compose.test.yml build --pull
          docker compose -f docker-compose.test.yml up -d \
          --wait --wait-timeout 120 security

      - name: Run pytest in security container
        run: |
          docker compose -f docker-compose.test.yml run --rm security \
            pytest --disable-warnings --tb=no

      - name: Final docker cleanup
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down -v --remove-orphans
          docker system prune -af
