name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: docker/cache-action@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build & start all services
        run: |
          docker compose -f docker-compose.test.yml build --pull
          docker compose -f docker-compose.test.yml up -d \
            --wait --wait-timeout 120

      - name: Run security integration tests
        run: docker compose -f docker-compose.test.yml exec -T security \
               pytest --disable-warnings --tb=no

      - name: Tear everything down
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down -v --remove-orphans
