# GitHub Action for building and pushing to private Docker registry

name: Build and Push to Private Registry

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: capstone-samfms.dns.net.za:443
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Private Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Extract repository name
      id: repo
      run: echo "name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
        
    - name: Generate image tags
      id: meta
      run: |
        REPO_NAME="${{ steps.repo.outputs.name }}"
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        COMMIT_SHA=${GITHUB_SHA::7}
        
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          TAGS="${{ env.REGISTRY }}/${REPO_NAME}:pr-${{ github.event.number }}"
        else
          TAGS="${{ env.REGISTRY }}/${REPO_NAME}:${BRANCH_NAME},${{ env.REGISTRY }}/${REPO_NAME}:${COMMIT_SHA}"
          if [ "${BRANCH_NAME}" = "main" ] || [ "${BRANCH_NAME}" = "master" ]; then
            TAGS="${TAGS},${{ env.REGISTRY }}/${REPO_NAME}:latest"
          fi
        fi
        
        echo "tags=${TAGS}" >> $GITHUB_OUTPUT
        echo "repo-name=${REPO_NAME}" >> $GITHUB_OUTPUT
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Output image details
      run: |
        echo "✅ Successfully built and pushed:"
        echo "Repository: ${{ steps.meta.outputs.repo-name }}"
        echo "Tags: ${{ steps.meta.outputs.tags }}"
        echo ""
        echo "🐳 Pull command:"
        echo "docker pull ${{ env.REGISTRY }}/${{ steps.meta.outputs.repo-name }}:${GITHUB_REF#refs/heads/}"
