name: Integration Tests (SAMDS)

on:
  workflow_dispatch:
  push:
    branches: [ main, development ]
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: docker-compose.integration.yml
      # If you trigger an external test orchestration endpoint, set this secret/var:
      SAMDS_TRIGGER_URL: ${{ vars.SAMDS_TRIGGER_URL }}
      SAMDS_TRIGGER_METHOD: POST

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build images
        run: docker compose -f "$COMPOSE_FILE" build

      - name: Run tests locally (compose)
        run: |
          chmod +x ./run-integration-tests.sh
          ./run-integration-tests.sh --logs

      # OPTIONAL: trigger remote SAMDS and validate response code (fixes the always-true comparison)
      - name: Trigger SAMDS endpoint (optional)
        if: ${{ env.SAMDS_TRIGGER_URL != '' }}
        run: |
          echo "Triggering: ${SAMDS_TRIGGER_METHOD:-POST} ${SAMDS_TRIGGER_URL}"
          response=$(curl -s -o /dev/null -w "%{http_code}" -X "${SAMDS_TRIGGER_METHOD:-POST}" "${SAMDS_TRIGGER_URL}")
          echo "HTTP response: $response"

          if [ "$response" -ge 200 ] && [ "$response" -lt 300 ]; then
            echo "✅ Integration tests completed successfully (remote trigger)"
          elif [ "$response" -ge 500 ] && [ "$response" -lt 600 ]; then
            echo "❌ Integration tests failed (server error, HTTP $response)"
            exit 1
          else
            echo "❌ Failed to trigger integration tests (HTTP $response)"
            exit 1
          fi
